import org.apache.shiro.codec.Hex;
import org.apache.shiro.crypto.AesCipherService;
import org.apache.shiro.util.Factory;

public final class RandomKey1 implements Factory<String> {

    /**
     * Prefix for hex-encoded strings.
     */
    private static final String PREFIX = "0x"; //$NON-NLS-1$

    /**
     * JavaBeans compatible no-argument constructor.
     */
    public RandomKey1() {
        super();
    }

    /**
     * Gets the key generated by the factory.
     * @return A random hex-encoded AES key.
     */
    @Override
    public String getInstance() {
        try {
            byte[] k = new AesCipherService().generateNewKey().getEncoded();
            String key =
                PREFIX
                + Hex.encodeToString(
                    k
                );
            System.out.println("*********************** Key: " + key);
            return key;
        } catch (Exception e) {
            e.printStackTrace();
            throw(e);
        }
    }

    public static void main(String[] args) {
        RandomKey1 randomKey11 = new RandomKey1();
        System.out.println(randomKey11.getInstance());
    }

}